// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// multi_mu_bar_fn
NumericMatrix multi_mu_bar_fn(NumericMatrix b, NumericVector prob);
RcppExport SEXP _mich_multi_mu_bar_fn(SEXP bSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(multi_mu_bar_fn(b, prob));
    return rcpp_result_gen;
END_RCPP
}
// muTLmu_bar_fn
NumericVector muTLmu_bar_fn(NumericMatrix QTb, NumericVector prob, NumericVector lambda, NumericMatrix mean_weights);
RcppExport SEXP _mich_muTLmu_bar_fn(SEXP QTbSEXP, SEXP probSEXP, SEXP lambdaSEXP, SEXP mean_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type QTb(QTbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mean_weights(mean_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(muTLmu_bar_fn(QTb, prob, lambda, mean_weights));
    return rcpp_result_gen;
END_RCPP
}
// mu_bar_fn
NumericVector mu_bar_fn(NumericVector b, NumericVector prob);
RcppExport SEXP _mich_mu_bar_fn(SEXP bSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(mu_bar_fn(b, prob));
    return rcpp_result_gen;
END_RCPP
}
// mu2_bar_fn
NumericVector mu2_bar_fn(NumericVector b, NumericVector omega, NumericVector prob);
RcppExport SEXP _mich_mu2_bar_fn(SEXP bSEXP, SEXP omegaSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(mu2_bar_fn(b, omega, prob));
    return rcpp_result_gen;
END_RCPP
}
// lambda_bar_fn
NumericVector lambda_bar_fn(NumericVector u, NumericVector v, NumericVector prob);
RcppExport SEXP _mich_lambda_bar_fn(SEXP uSEXP, SEXP vSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_bar_fn(u, v, prob));
    return rcpp_result_gen;
END_RCPP
}
// mu_lambda_fn
NumericVector mu_lambda_fn(NumericVector b, NumericVector u, NumericVector v, NumericVector prob);
RcppExport SEXP _mich_mu_lambda_fn(SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(mu_lambda_fn(b, u, v, prob));
    return rcpp_result_gen;
END_RCPP
}
// mu2_lambda_fn
NumericVector mu2_lambda_fn(NumericVector b, NumericVector omega, NumericVector u, NumericVector v, NumericVector prob);
RcppExport SEXP _mich_mu2_lambda_fn(SEXP bSEXP, SEXP omegaSEXP, SEXP uSEXP, SEXP vSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(mu2_lambda_fn(b, omega, u, v, prob));
    return rcpp_result_gen;
END_RCPP
}
// mich_cpp
List mich_cpp(NumericVector y, int J, int L, int K, NumericVector mu_0_vec, NumericVector lambda_0_vec, bool fit_intercept, bool fit_scale, double max_iter, bool verbose, double tol, double omega_j, double u_j, double v_j, NumericMatrix log_pi_j, NumericMatrix pi_bar_j, NumericMatrix log_pi_bar_j, NumericMatrix b_bar_j, NumericMatrix omega_bar_j, NumericVector u_bar_j, NumericMatrix v_bar_j, NumericVector lgamma_u_bar_j, NumericVector digamma_u_bar_j, double omega_l, NumericMatrix log_pi_l, NumericMatrix pi_bar_l, NumericMatrix log_pi_bar_l, NumericMatrix b_bar_l, NumericMatrix omega_bar_l, double u_k, double v_k, NumericMatrix log_pi_k, NumericMatrix pi_bar_k, NumericMatrix log_pi_bar_k, NumericVector u_bar_k, NumericMatrix v_bar_k, NumericVector lgamma_u_bar_k, NumericVector digamma_u_bar_k);
RcppExport SEXP _mich_mich_cpp(SEXP ySEXP, SEXP JSEXP, SEXP LSEXP, SEXP KSEXP, SEXP mu_0_vecSEXP, SEXP lambda_0_vecSEXP, SEXP fit_interceptSEXP, SEXP fit_scaleSEXP, SEXP max_iterSEXP, SEXP verboseSEXP, SEXP tolSEXP, SEXP omega_jSEXP, SEXP u_jSEXP, SEXP v_jSEXP, SEXP log_pi_jSEXP, SEXP pi_bar_jSEXP, SEXP log_pi_bar_jSEXP, SEXP b_bar_jSEXP, SEXP omega_bar_jSEXP, SEXP u_bar_jSEXP, SEXP v_bar_jSEXP, SEXP lgamma_u_bar_jSEXP, SEXP digamma_u_bar_jSEXP, SEXP omega_lSEXP, SEXP log_pi_lSEXP, SEXP pi_bar_lSEXP, SEXP log_pi_bar_lSEXP, SEXP b_bar_lSEXP, SEXP omega_bar_lSEXP, SEXP u_kSEXP, SEXP v_kSEXP, SEXP log_pi_kSEXP, SEXP pi_bar_kSEXP, SEXP log_pi_bar_kSEXP, SEXP u_bar_kSEXP, SEXP v_bar_kSEXP, SEXP lgamma_u_bar_kSEXP, SEXP digamma_u_bar_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_0_vec(mu_0_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda_0_vec(lambda_0_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type fit_intercept(fit_interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type fit_scale(fit_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type omega_j(omega_jSEXP);
    Rcpp::traits::input_parameter< double >::type u_j(u_jSEXP);
    Rcpp::traits::input_parameter< double >::type v_j(v_jSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_pi_j(log_pi_jSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pi_bar_j(pi_bar_jSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_pi_bar_j(log_pi_bar_jSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_bar_j(b_bar_jSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type omega_bar_j(omega_bar_jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u_bar_j(u_bar_jSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v_bar_j(v_bar_jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lgamma_u_bar_j(lgamma_u_bar_jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type digamma_u_bar_j(digamma_u_bar_jSEXP);
    Rcpp::traits::input_parameter< double >::type omega_l(omega_lSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_pi_l(log_pi_lSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pi_bar_l(pi_bar_lSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_pi_bar_l(log_pi_bar_lSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_bar_l(b_bar_lSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type omega_bar_l(omega_bar_lSEXP);
    Rcpp::traits::input_parameter< double >::type u_k(u_kSEXP);
    Rcpp::traits::input_parameter< double >::type v_k(v_kSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_pi_k(log_pi_kSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pi_bar_k(pi_bar_kSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_pi_bar_k(log_pi_bar_kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u_bar_k(u_bar_kSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v_bar_k(v_bar_kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lgamma_u_bar_k(lgamma_u_bar_kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type digamma_u_bar_k(digamma_u_bar_kSEXP);
    rcpp_result_gen = Rcpp::wrap(mich_cpp(y, J, L, K, mu_0_vec, lambda_0_vec, fit_intercept, fit_scale, max_iter, verbose, tol, omega_j, u_j, v_j, log_pi_j, pi_bar_j, log_pi_bar_j, b_bar_j, omega_bar_j, u_bar_j, v_bar_j, lgamma_u_bar_j, digamma_u_bar_j, omega_l, log_pi_l, pi_bar_l, log_pi_bar_l, b_bar_l, omega_bar_l, u_k, v_k, log_pi_k, pi_bar_k, log_pi_bar_k, u_bar_k, v_bar_k, lgamma_u_bar_k, digamma_u_bar_k));
    return rcpp_result_gen;
END_RCPP
}
// mich_matrix_cpp
List mich_matrix_cpp(NumericMatrix y, NumericVector mu_0, NumericVector lambda, NumericVector log_lambda, NumericMatrix Q, NumericVector Lambda_bar_log_det, NumericVector inv_Lambda_bar_trace, NumericMatrix mean_weights, NumericMatrix sandwich_weights, NumericMatrix log_prob_weights, bool fit_intercept, bool fit_scale, double max_iter, double tol, bool verbose, double omega_l, double log_omega_l, double d_log_omega_l, NumericMatrix log_pi_l, List post_params);
RcppExport SEXP _mich_mich_matrix_cpp(SEXP ySEXP, SEXP mu_0SEXP, SEXP lambdaSEXP, SEXP log_lambdaSEXP, SEXP QSEXP, SEXP Lambda_bar_log_detSEXP, SEXP inv_Lambda_bar_traceSEXP, SEXP mean_weightsSEXP, SEXP sandwich_weightsSEXP, SEXP log_prob_weightsSEXP, SEXP fit_interceptSEXP, SEXP fit_scaleSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP omega_lSEXP, SEXP log_omega_lSEXP, SEXP d_log_omega_lSEXP, SEXP log_pi_lSEXP, SEXP post_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_0(mu_0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_lambda(log_lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Q(QSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Lambda_bar_log_det(Lambda_bar_log_detSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type inv_Lambda_bar_trace(inv_Lambda_bar_traceSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mean_weights(mean_weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sandwich_weights(sandwich_weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_prob_weights(log_prob_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type fit_intercept(fit_interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type fit_scale(fit_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type omega_l(omega_lSEXP);
    Rcpp::traits::input_parameter< double >::type log_omega_l(log_omega_lSEXP);
    Rcpp::traits::input_parameter< double >::type d_log_omega_l(d_log_omega_lSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_pi_l(log_pi_lSEXP);
    Rcpp::traits::input_parameter< List >::type post_params(post_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(mich_matrix_cpp(y, mu_0, lambda, log_lambda, Q, Lambda_bar_log_det, inv_Lambda_bar_trace, mean_weights, sandwich_weights, log_prob_weights, fit_intercept, fit_scale, max_iter, tol, verbose, omega_l, log_omega_l, d_log_omega_l, log_pi_l, post_params));
    return rcpp_result_gen;
END_RCPP
}
// mean_scp
List mean_scp(NumericVector y, NumericVector lambda, double omega, double log_omega, NumericVector log_pi);
RcppExport SEXP _mich_mean_scp(SEXP ySEXP, SEXP lambdaSEXP, SEXP omegaSEXP, SEXP log_omegaSEXP, SEXP log_piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type log_omega(log_omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_pi(log_piSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_scp(y, lambda, omega, log_omega, log_pi));
    return rcpp_result_gen;
END_RCPP
}
// multi_mean_scp
List multi_mean_scp(NumericMatrix QTr, NumericVector lambda, NumericMatrix mean_weights, NumericMatrix sandwich_weights, NumericVector log_prob_weights);
RcppExport SEXP _mich_multi_mean_scp(SEXP QTrSEXP, SEXP lambdaSEXP, SEXP mean_weightsSEXP, SEXP sandwich_weightsSEXP, SEXP log_prob_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type QTr(QTrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mean_weights(mean_weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sandwich_weights(sandwich_weightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_prob_weights(log_prob_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(multi_mean_scp(QTr, lambda, mean_weights, sandwich_weights, log_prob_weights));
    return rcpp_result_gen;
END_RCPP
}
// var_scp
List var_scp(NumericVector y, NumericVector omega, NumericVector u_bar, NumericVector lgamma_u_bar, NumericVector v, double log_v, NumericVector log_pi);
RcppExport SEXP _mich_var_scp(SEXP ySEXP, SEXP omegaSEXP, SEXP u_barSEXP, SEXP lgamma_u_barSEXP, SEXP vSEXP, SEXP log_vSEXP, SEXP log_piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u_bar(u_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lgamma_u_bar(lgamma_u_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type log_v(log_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_pi(log_piSEXP);
    rcpp_result_gen = Rcpp::wrap(var_scp(y, omega, u_bar, lgamma_u_bar, v, log_v, log_pi));
    return rcpp_result_gen;
END_RCPP
}
// meanvar_scp
List meanvar_scp(NumericVector y, NumericVector lambda, double omega, double log_omega, NumericVector u_bar, NumericVector lgamma_u_bar, NumericVector v, double log_v, NumericVector log_pi);
RcppExport SEXP _mich_meanvar_scp(SEXP ySEXP, SEXP lambdaSEXP, SEXP omegaSEXP, SEXP log_omegaSEXP, SEXP u_barSEXP, SEXP lgamma_u_barSEXP, SEXP vSEXP, SEXP log_vSEXP, SEXP log_piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type log_omega(log_omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u_bar(u_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lgamma_u_bar(lgamma_u_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type log_v(log_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_pi(log_piSEXP);
    rcpp_result_gen = Rcpp::wrap(meanvar_scp(y, lambda, omega, log_omega, u_bar, lgamma_u_bar, v, log_v, log_pi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mich_multi_mu_bar_fn", (DL_FUNC) &_mich_multi_mu_bar_fn, 2},
    {"_mich_muTLmu_bar_fn", (DL_FUNC) &_mich_muTLmu_bar_fn, 4},
    {"_mich_mu_bar_fn", (DL_FUNC) &_mich_mu_bar_fn, 2},
    {"_mich_mu2_bar_fn", (DL_FUNC) &_mich_mu2_bar_fn, 3},
    {"_mich_lambda_bar_fn", (DL_FUNC) &_mich_lambda_bar_fn, 3},
    {"_mich_mu_lambda_fn", (DL_FUNC) &_mich_mu_lambda_fn, 4},
    {"_mich_mu2_lambda_fn", (DL_FUNC) &_mich_mu2_lambda_fn, 5},
    {"_mich_mich_cpp", (DL_FUNC) &_mich_mich_cpp, 38},
    {"_mich_mich_matrix_cpp", (DL_FUNC) &_mich_mich_matrix_cpp, 20},
    {"_mich_mean_scp", (DL_FUNC) &_mich_mean_scp, 5},
    {"_mich_multi_mean_scp", (DL_FUNC) &_mich_multi_mean_scp, 5},
    {"_mich_var_scp", (DL_FUNC) &_mich_var_scp, 7},
    {"_mich_meanvar_scp", (DL_FUNC) &_mich_meanvar_scp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_mich(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
