# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mich_cpp <- function(y, J, L, K, mu_0, lambda_0, fit_intercept, fit_scale, refit, max_iter, verbose, tol, omega_j, u_j, v_j, log_pi_j, pi_bar_j, log_pi_bar_j, b_bar_j, omega_bar_j, u_bar_j, v_bar_j, lgamma_u_bar_j, digamma_u_bar_j, omega_l, log_pi_l, pi_bar_l, log_pi_bar_l, b_bar_l, omega_bar_l, u_k, v_k, log_pi_k, pi_bar_k, log_pi_bar_k, u_bar_k, v_bar_k, lgamma_u_bar_k, digamma_u_bar_k) {
    .Call(`_mich_mich_cpp`, y, J, L, K, mu_0, lambda_0, fit_intercept, fit_scale, refit, max_iter, verbose, tol, omega_j, u_j, v_j, log_pi_j, pi_bar_j, log_pi_bar_j, b_bar_j, omega_bar_j, u_bar_j, v_bar_j, lgamma_u_bar_j, digamma_u_bar_j, omega_l, log_pi_l, pi_bar_l, log_pi_bar_l, b_bar_l, omega_bar_l, u_k, v_k, log_pi_k, pi_bar_k, log_pi_bar_k, u_bar_k, v_bar_k, lgamma_u_bar_k, digamma_u_bar_k)
}

#' Multivariate MICH Algorithm
#'
#' @description
#' Implementation of Algorithm 3 from Berlind, Cappello, and Madrid Padilla
#' (2025). This algorithm takes a sequence of \eqn{d}-dimensional observations
#' \eqn{\mathbf{y}_{1:T}}, and iteratively fits \eqn{L} mean-scp models
#' resulting in a variational approximation to the posterior distribution of
#' the \eqn{L} mean change-points. The algorithm terminates once the
#' percentage increase in the ELBO falls below `tol`.
#'
#' @param y A numeric matrix. \eqn{T \times N} matrix of observations.
#' @param mu_0 A numeric vector. Vector of intercept parameters.
#' @param fit_intercept A logical. If `fit_intercept == TRUE`, then an
#'   intercept is estimated and `mu_0` gets updated.
#' @param refit A logical. If `refit == TRUE`, then the MICH algorithm is
#'   initialized by the fit provided in `post_params`, otherwise the null
#'   model \eqn{\boldsymbol{\mu}_t = \mathbf{0}} and
#'   \eqn{\bar{\pi}_{\ell t} = 1/T} is used as the initialization.
#' @param max_iter An integer. Maximum number of iterations. If ELBO does not
#'   converge before `max_iter` is reached, then `converged == FALSE` in the
#'   returned fit object.
#' @param tol A scalar. Convergence tolerance for relative increase in ELBO.
#' @param verbose A logical. If `verbose == TRUE`, then value of the ELBO is
#'   printed every 5000th iteration.
#' @param omega_bar_l,log_omega_bar_l Numeric vectors. Vector of posterior
#'   precision parameters \eqn{\{\bar{\omega}_t\}_{t=1}^T} and log evaluations
#'   such that \eqn{V(\mathbf{b}_\ell|\tau=t) = \bar{\omega}_t\mathbf{I}_d}.
#' @param post_params A list. A length \eqn{L} list of the posterior parameters
#'   of each mean-scp component. Each element of the list is a list containing
#'   a \eqn{T\times L} matrix of posterior mean parameters and length \eqn{T}
#'   vectors of posterior change-point location probabilities and their log
#'   evaluations.
#'
#' @return A List. Parameters of the variational approximation the MICH
#' posterior distribution, including:
#'   * `residual`: A numeric vector. Residual \eqn{\mathbf{r}_{1:T}} after
#'     subtracting out each \eqn{E[\boldsymbol{\mu}_{\ell t}]} from
#'     \eqn{\mathbf{y}_{1:T}}.
#'   * `mu`: A numeric matrix. Posterior estimate of
#'     \eqn{\Sigma_{\ell=1}^L E[\boldsymbol{\mu}_{\ell,1:T}|\mathbf{y}_{1:T}]}.
#'   * `mu_0`: A numeric vector. Estimate of the intercept.
#'   * `post_params`: A list. List of posterior parameters for each mean-scp
#'     component.
#'   * `elbo`: A numeric vector. Value of the ELBO after each iteration.
#'   * `converged`: A logical. Indicates whether relative increase in the ELBO
#'     is less than `tol`.
#'
multi_mich_cpp <- function(y, mu_0, fit_intercept, refit, max_iter, tol, verbose, omega_l, log_pi_l, omega_bar_l, log_omega_bar_l, post_params) {
    .Call(`_mich_multi_mich_cpp`, y, mu_0, fit_intercept, refit, max_iter, tol, verbose, omega_l, log_pi_l, omega_bar_l, log_omega_bar_l, post_params)
}

#' Mean Single Change-Point Model
#'
#' @description
#' Implementation of the univariate Mean-SCP model from Berlind, Cappello, and
#' Madrid Padilla (2025). The function `mean_scp()` takes a length \eqn{T}
#' vector \eqn{y_{1:T}} with a single mean change and returns the posterior
#' distribution of the change-point.
#'
#' @param y A numeric vector. \eqn{T} observations with a single variance
#'   change.
#' @param lambda A numeric vector. Precision vector of `y`.
#' @param omega A positive scalar. Prior precision parameter.
#' @param log_pi A numeric vector. Vector of log prior probabilities for the
#'   location of the change-point.
#'
#' @return A list. A list of posterior parameters including the mean `b_bar`,
#' precision `omega_bar`, and posterior probabilities of the change-point
#' location `pi_bar`.
#'
#' @export
#'
mean_scp <- function(y, lambda, omega, log_pi) {
    .Call(`_mich_mean_scp`, y, lambda, omega, log_pi)
}

#' Mulitvariate Mean Single Change-Point Model
#'
#' @description
#' Implementation of the multivariate Mean-SCP model from Berlind, Cappello,
#' and Madrid Padilla (2025). The function `mean_scp()` takes a \eqn{T\times d}
#' matrix \eqn{\mathbf{y}_{1:T}} with a single mean change and returns the
#' posterior distribution of the change-point.
#'
#' @param y A numeric matrix. \eqn{T\times d} matrix of observations with a
#'   single mean change.
#' @param omega_bar A numeric vector. Posterior precision parameters
#'   \eqn{\bar{\omega}_t} such that
#'   \eqn{\bar{\Omega}_t = \bar{\omega}_t\mathbf{I}_d}.
#' @param log_omega_bar A numeric vector. Log of `omega_bar`.
#' @param log_pi A numeric vector. Vector of log prior probabilities for the
#'   location of the change-point.
#'
#' @return A list. A list of posterior parameters including the mean `b_bar`,
#' and posterior probabilities of the change-point location `pi_bar`.
#'
#' @export
#'
multi_mean_scp <- function(y, omega_bar, log_omega_bar, log_pi) {
    .Call(`_mich_multi_mean_scp`, y, omega_bar, log_omega_bar, log_pi)
}

#' Variance Single Change-Point Model
#'
#' @description
#' Implementation of the Var-SCP model from Berlind, Cappello, and Madrid
#' Padilla (2025). The function `var_scp()` takes a length \eqn{T} vector
#' \eqn{y_{1:T}} with a single variance change and returns the posterior
#' distribution of the change-point.
#'
#' @param y A numeric vector. \eqn{T} observations with a single variance
#'   change.
#' @param omega A numeric vector. Known trend component of precision of `y`.
#' @param u_bar A numeric vector. Posterior shape parameters equal to
#'   \eqn{u_0 + T - t + 1} for each \eqn{t}.
#' @param lgamma_u_bar A numeric vector. Log gamma function evaluated at u_bar.
#' @param v A numeric vector. Vector of prior rate parameters for each \eqn{t}.
#' @param log_pi A numeric vector. Vector of log prior probabilities for the
#'   location of the change-point.
#'
#' @return A list. A list of posterior parameters including the rate `v_bar`,
#' and posterior probabilities of the change-point location `pi_bar`.
#'
#' @export
#'
var_scp <- function(y, omega, u_bar, lgamma_u_bar, v, log_pi) {
    .Call(`_mich_var_scp`, y, omega, u_bar, lgamma_u_bar, v, log_pi)
}

#' Mean-Variance Single Change-Point Model
#'
#' @description
#' Implementation of the MeanVar-SCP model from Berlind, Cappello, and Madrid
#' Padilla (2025). The function `meanvar_scp()` takes a length \eqn{T} vector
#' \eqn{y_{1:T}} with a single joint mean and variance change and returns the
#' posterior distribution of the change-point.
#'
#' @param y A numeric vector. \eqn{T} observations with a single joint mean and
#' variance change.
#' @param lambda A numeric vector. Known trend component of precision of `y`.
#' @param omega A positive scalar. Prior precision parameter.
#' @param u_bar A numeric vector. Posterior shape parameters equal to
#'   \eqn{u_0 + T - t + 1} for each \eqn{t}.
#' @param lgamma_u_bar A numeric vector. Log gamma function evaluated at u_bar.
#' @param v A numeric vector. Vector of prior rate parameters for each \eqn{t}.
#' @param log_pi A numeric vector. Vector of log prior probabilities for the
#'   location of the change-point.
#'
#' @return A list. A list of posterior parameters including the  mean `b_bar`,
#' precision `omega_bar`, rate `v_bar`, and posterior probabilities of the
#' change-point location `pi_bar`.
#'
#' @export
#'
meanvar_scp <- function(y, lambda, omega, u_bar, lgamma_u_bar, v, log_pi) {
    .Call(`_mich_meanvar_scp`, y, lambda, omega, u_bar, lgamma_u_bar, v, log_pi)
}

